openapi: 3.0.3
info:
  title: Shiritori Service
  description: HTTP service for adding numbers, a goa teaser
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /:
    get:
      tags:
      - shiritori
      summary: Download ./frontend/index.html
      operationId: shiritori#/
      responses:
        "200":
          description: File downloaded
  /add/{a}/{b}:
    get:
      tags:
      - shiritori
      summary: add shiritori
      operationId: shiritori#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 9013565148345874905
          format: int64
        example: 1511986039251284080
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 5380863506013512516
          format: int64
        example: 4551435967266391722
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 7341786561015235771
                format: int64
              example: 6403480038048273120
  /streams/battles/{battleId}:
    get:
      tags:
      - shiritori
      summary: battle shiritori
      operationId: shiritori#battle
      parameters:
      - name: battleId
        in: path
        required: true
        schema:
          type: string
          example: Nihil quasi praesentium et.
        example: Et sed deleniti nihil.
      responses:
        "101":
          description: Switching Protocols response.
          content:
            application/json:
              schema:
                description: 'Response body may alternatively be #/components/schemas/BattleResponseBodyOther'
                $ref: '#/components/schemas/Battleevent'
              example:
                battleId: Commodi tempora sint tempore.
                name: Reiciendis labore unde sed recusandae nam.
                param: Sit ut ea eum odit laboriosam.
  /words/{word}:
    get:
      tags:
      - shiritori
      summary: words shiritori
      operationId: shiritori#words
      parameters:
      - name: word
        in: path
        required: true
        schema:
          type: string
          example: Dolor sed vel modi nemo unde.
        example: Explicabo cupiditate necessitatibus fugit.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wordresult'
              example:
                exists: true
                hash: Qui dolores tenetur.
                word: Est autem nesciunt quo.
components:
  schemas:
    BattleResponseBodyOther:
      type: object
      properties:
        battleId:
          type: string
          example: Qui eius.
        name:
          type: string
          example: Quae ullam.
        param:
          type: string
          example: Et id aut.
      description: BattleResponseBody result type (other view)
      example:
        battleId: Explicabo laboriosam dolorem.
        name: Consectetur laboriosam commodi alias sit.
        param: Laborum rem deleniti.
    BattleStreamingBody:
      $ref: '#/components/schemas/BattleStreamingBody'
    Battleevent:
      type: object
      properties:
        battleId:
          type: string
          example: Et vero at harum et et quaerat.
        name:
          type: string
          example: Reprehenderit quaerat ratione quas aut.
        param:
          type: string
          example: Accusantium id deserunt.
      example:
        battleId: Suscipit neque mollitia dolorem asperiores reprehenderit.
        name: Et fugit optio illo repellendus non nihil.
        param: Sit doloribus aut autem.
    Wordresult:
      type: object
      properties:
        exists:
          type: boolean
          example: false
        hash:
          type: string
          example: Quia quo.
        word:
          type: string
          example: Sit exercitationem tempora accusantium ipsa in cum.
      example:
        exists: false
        hash: Fuga recusandae.
        word: Non qui debitis.
      required:
      - word
      - hash
      - exists
