swagger: "2.0"
info:
  title: Shiritori Service
  description: HTTP service for adding numbers, a goa teaser
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - shiritori
      summary: Download ./frontend/index.html
      operationId: shiritori#/
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /add/{a}/{b}:
    get:
      tags:
      - shiritori
      summary: add shiritori
      operationId: shiritori#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /streams/battles/{battleId}:
    get:
      tags:
      - shiritori
      summary: battle shiritori
      operationId: shiritori#battle
      parameters:
      - name: battleId
        in: path
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ShiritoriBattleResponseBody'
      schemes:
      - ws
  /words/{word}:
    get:
      tags:
      - shiritori
      summary: words shiritori
      operationId: shiritori#words
      parameters:
      - name: word
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ShiritoriWordsResponseBody'
      schemes:
      - http
definitions:
  MessagePayloadResponseBody:
    title: MessagePayloadResponseBody
    type: object
    properties:
      message:
        type: string
        example: Commodi tempora sint tempore.
    example:
      message: Reiciendis labore unde sed recusandae nam.
    required:
    - message
  ShiritoriBattleResponseBody:
    title: 'Mediatype identifier: battlestreamingresult; view=default'
    type: object
    properties:
      message_payload:
        $ref: '#/definitions/MessagePayloadResponseBody'
      timestamp:
        type: integer
        example: 1731503209999601179
        format: int64
      type:
        type: string
        example: Ut et architecto excepturi.
    description: BattleResponseBody result type (default view)
    example:
      message_payload:
        message: Quam cumque voluptatem.
      timestamp: 5795481755208264950
      type: Sit ut ea eum odit laboriosam.
    required:
    - type
    - timestamp
  ShiritoriWordsResponseBody:
    title: 'Mediatype identifier: wordresult; view=default'
    type: object
    properties:
      exists:
        type: boolean
        example: true
      hash:
        type: string
        example: Eos hic.
      word:
        type: string
        example: Aut animi id ipsam vero.
    description: WordsResponseBody result type (default view)
    example:
      exists: true
      hash: Dolor eos aut qui eos ducimus ipsum.
      word: Suscipit sapiente est temporibus repudiandae voluptate.
    required:
    - word
    - hash
    - exists
